# Build: $ docker-compose build
# Run: $ docker-compose up -d
# Stop: $ docker-compose down

version: '3'
services: 
    backend:
        build: ./backend
        container_name: backend
        ports: 
            - 8080:8080
    frontend:
        build: ./frontend
        container_name: frontend
        ports:
            - 80:80
        links:
            - backend
